### ISSUE TITLE
Focus on single driver

### ISSUE THREAD

**Issue by mrzoops** [MerlinCooper/iRacingReplayDirector#100]
Just wanted to jump in here and say that the logic behind following preferred drivers seems to be way off. There should be a simple option to hard limit the highlight video to ONLY follow a specific player or two. I get so many highlights where its people sitting in the pits, other cars driving around doing nothing. I want a highlight video of MY race only. Is that possible to implement?

**Comment by MerlinCooper** [comment]
What mode /settings are you using? Might make a difference whether it‘s the classic or fast way.

**Comment by MerlinCooper** [comment]
Please post a screenshot of the about dialog as well

**Comment by MerlinCooper** [comment]
That's an exact copy of the feature request #28 

Therefore I am closing this issue - discussion and improvement can be tracked in issue #28
