### ISSUE TITLE
Transcode problem - issue taken over from vipoo fork

### ISSUE THREAD

**Issue by MerlinCooper** [MerlinCooper/iRacingReplayDirector#13]
vipoo/iRacingReplayOverlay.net#114

**Comment by Agent12253** [comment]
Has this been resolved somewhere else?  I am using the 1.02.04 beta and am having this issue.

**Comment by MerlinCooper** [comment]
Root cause for the failure is not identified yet.

Given the fact that the whole sequential process (analys, record, transcode) is taking a lot of time l'm working on a different approach where just the highlights will be recorded and not the full video has to be recorded.

Solution will work with OBS only and overlays will have to be done in OBS.

Can't provide a firm timing but trying to achieve a first working beta for testing in 05/2020

Not sure by when it will be ready

**Comment by MerlinCooper** [comment]
Duplicate
