### ISSUE TITLE
Recording Software currently used together with iRacingReplayDirector 

### ISSUE THREAD

**Issue by MerlinCooper** [MerlinCooper/iRacingReplayDirector#29]
Would be happy to get feedback what recording software everyone is using as of now together with iRacingReplayDirector. Would you guys be fine if it will work only together with OBS in the future?

**Comment by MerlinCooper** [comment]
closed with 3f69a3bfbd650d66d84f6484348be50be8e398c0

**Comment by kareem613** [comment]
I think keeping the dependencies to a minimum is a good idea. 
The current implementation with the windows built in recorder keeps it simpler for people using it. 

I'm sure an interface (iRecorder?) could be put in place abstracting away implementations for the windows recorder and OBS. 
What's needed from the recording software? Start, stop, and knowing where the files end up. Anything else?

**Comment by MerlinCooper** [comment]
> I think keeping the dependencies to a minimum is a good idea.
> The current implementation with the windows built in recorder keeps it simpler for people using it.

Not sure whether I do understand your point. The application is not using a windows built in recorder at the moment. It just controls a third party application by sending key-strokes. This caused issues in the past where people either did the shortkeys wrong or did use wrong video format/compression. 


> I'm sure an interface (iRecorder?) could be put in place abstracting away implementations for the windows recorder and OBS.
Three is already an API available. Did not look into the details so far - but the effort seems to be manageble to remotely control OBS. 

> What's needed from the recording software? Start, stop, and knowing where the files end up. Anything else?
The application is working in the three phases (analysis, capture, transcode). That sound about right until you recognize that the raceEvents to be captured are not identified in the analysis phase - instead they are identfied during the capture phase by recording a full length video of the replay which will be "shortened" to the interesting parts during transcode. That's fine (although not fast) for replay lengths up to an 1-2 hrs. But if the replay is longer it does mean spending time to record scenes which will but cut out anyway because nothing is happening. 

Thus I took a different approach in the Fast_Video_Recording branch I'm currently working on. 
https://github.com/MerlinCooper/iRacingReplayDirector/tree/Fast_Video_Recording_With_OBS

The major difference is that the raceEvents will be identfied in the analysis phase w/o recording a video and using FF16x. During the capture phase only the raceHighlights (depending on the target length of the video) will be recorded. That requires a possiblity to "pause" the recording or an implementation to concatenate different videos.

**Comment by MerlinCooper** [comment]
By the way the classes used for trancoding the video are outdated as well. Would be something on the todo list to update those anyway.

**Comment by kareem613** [comment]
I haven't looked in depth at how the recording works much. I'm only familiar with the replay controls so far. 

I really like the idea of only recording the highlights instead of it being a post process. Would make things go much quicker. 

Out of the box it works with the windows built in game bar recorder.  Alt-F9. That is built into windows 10. I don't think it has pause capability so it would just end up producing numerous files that would need to be concatenated. 

Ideally support for OBS wouldn't need to sacrifice support for other recorders. I'll take a deeper look to better understand that area and have better input.

**Comment by MerlinCooper** [comment]
> 
> 
> I haven't looked in depth at how the recording works much. I'm only familiar with the replay controls so far.

Suggest to wait until I'm finished with the work I'm doing in the separate branch - or look at how it's been done there. Analysis already is working by FF16x, recording of raceSceens is implemented as well, camera control when recording is missing though. 

> I really like the idea of only recording the highlights instead of it being a post process. Would make things go much quicker.

Pretty much done - see above. 

> Out of the box it works with the windows built in game bar recorder. Alt-F9. That is built into windows 10. I don't think it has pause capability so it would just end up producing numerous files that would need to be concatenated.

Understood. And there might be others not using OBS. Due very view recording applications do support pause/resume some code will have to be written to concatenate the files. And obviously this will require processing time again. There might be an opportunity to integrate the recording software directly into the application - but than some questions with regard to 3rd party overlay will be raised. 

> Ideally support for OBS wouldn't need to sacrifice support for other recorders. I'll take a deeper look to better understand that area and have better input.

Should be feasible and looks to like it could be covered within the class VideoCapture. 

P.S.: Next release will include an alpha version of the fast-recording approach. But obviously only together with recording software supporting pause/resume (tested with OBS only)

**Comment by kareem613** [comment]
> P.S.: Next release will include an alpha version of the fast-recording approach. But obviously only together with recording software supporting pause/resume (tested with OBS only)

I'll try it out for sure. 

Also, I just realized the recording software i'm using isn't Game Bar. It's the nvidia geforce experience. It has hotkey start/stop support (alt+F9). Works out of the box with replaydirector.

**Comment by petarpav28** [comment]
Sound good to me especially if it means a highlight video is done quicker. Already use OBS to record everything anyway.

**Comment by MerlinCooper** [comment]
> 
> 
> Sound good to me especially if it means a highlight video is done quicker. Already use OBS to record everything anyway.

That's exactly what I'm targeting with the "Fast video Recording" branch. You can download that and you will be surprised how fast the analysis is being done. At the end you can easily predict how long it will take. 

The analysis is being done by palying out the video in 16xFF. And afterwards only the selected highlight will be recorded - and therefore this will take at the end the time your highlight video lasts (plus a small overhead for seeking to the right replay position). 

As an example if you are doing a 20 min Highlight video of a 12 hrs race you will be done in approx. 65 min (=analysis 45min +20 min recording). At the moment the analysis will take 12 hrs (because analysis of highlights is being done while recording the video and afterwards the full video length is being transcoded to the highlight of 20min => more than 12 hrs. for a highlight video. 

P.S.: Version of fast transcoding still has issues - so consider it as an alpha version. Will try to spent some time during X-mas holidays to get it to a usable beta.
