### ISSUE TITLE
Collapsing overlay submodules

### ISSUE THREAD

**Issue by kareem613** [MerlinCooper/iRacingReplayDirector#36]
@MerlinCooper Do you see a benefit to the overlays being in their own submodules? I think it would simplify managing the solution if they were in the main repo. 
Just the overlays. The SDK makes sense on it's own because it can be used for other projects, but the overlays look pretty specific.

**Comment by MerlinCooper** [comment]
@kareem613 The solution is pretty much as setup by Vipoo - and frankly it's quite complicated given the large amount of submodules in the solution. But so far I did not want to start re-structuring the solution.

You are absolutely right that the overlay plugins are very specific to the iRacingReplayDirector. The only reason to keep the overlay's seperate would be to make it easier for people just develop an overlay plugin. But looking at the two repositories on github there are not a lot of people working on the overlay plugins anyway. 

Thus I'm fine with just adding the source code for the two available overlay-plugins as source code. 

Another option would be to just add the binary (.dll) to the iRacingReplayDirector and keep the overlay-plugins in separate (not linked) repositories.

**Comment by kareem613** [comment]
I don't mind handling the restructuring.
I'll collapse the overlay submodules and submit a PR.
I ran into this trying to update to framework 4.7.2. I see you already did the SDK. I can upgrade the director after collapsing there submodules.
