### ISSUE TITLE
Overlap / Stutter in recorded replay

### ISSUE THREAD

**Issue by MerlinCooper** [MerlinCooper/iRacingReplayDirector#43]
Belongs to the Fast-Replay-Recording only.

In case no driver change happens pausing/resuming the replay recording causes weird effects 

a) overlapping recordings
b) stuttering due to not seamless pause/resume

**Comment by mrzoops** [comment]
Tried the newest build today and the stuttering is still there. I tried using OBS but not sure how I should have the Start Recording and Pause Recording buttons mapped in OBS. I set Start Recording to F9 and that works, but the pausing is not working.

**Comment by MerlinCooper** [comment]
> 
> 
> Tried the newest build today and the stuttering is still there. I tried using OBS but not sure how I should have the Start Recording and Pause Recording buttons mapped in OBS. I set Start Recording to F9 and that works, but the pausing is not working.

Thanks for the feedback. Not unexpected that the stutter is still there because I just created a branch and did not change any code so far. 

With regard to the configuration issue I have to admit that the documentation is quite poor at the moment. Had to look up the code to remember what keystrokes are being used. At the moment ALT+F9 is used for stop/start and ALT+F10 is used for pause/resume created a separate issue for keeping track on that #52

**Comment by mrzoops** [comment]
Just an update still happening on latest build [20220515.3]

**Comment by MerlinCooper** [comment]
Yes - I‘m moving slowly there. Don‘t have a lot of time which I can spend on that topic.

**Comment by MerlinCooper** [comment]
close #43
