### ISSUE TITLE
ERROR: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by petarpav28** [MerlinCooper/iRacingReplayDirector#46]
Getting a ERROR: Index was outside the bounds of the array when trying to transcode the highlight only also happens when trying to transcode the full race as well.

Have tried multiple replay files all produce the same result. Using OBS to record the settings are as follow:-
![image](https://user-images.githubusercontent.com/74888241/99926893-656ebd80-2d97-11eb-805d-dd79d3c93939.png)

Have also tried with CPU x264 encoding with the following settings
![image](https://user-images.githubusercontent.com/74888241/99926938-8800d680-2d97-11eb-8806-057ca435fd7a.png)

I'm using the 2019-11.V.1.04.02-beta.Binaries with overlay set to NoOverlay, all files have been unblocked.

Not sure what else you need. 
[2020-11-23_11-37-35.log](https://github.com/MerlinCooper/iRacingReplayDirector/files/5581000/2020-11-23_11-37-35.log)

**Comment by MerlinCooper** [comment]
The app doesn't support a lot of codec's. Supported video formats still have the [limitations as described by vipoo.](https://github.com/MerlinCooper/iRacingReplayDirector#known-issuesrequirements).

Anyway I do not see from your screenshots what is really causing the issue. Although I'm pretty sure that it doesn't have to do anything with the replay file. Have you tryed "Verify Video Capture"? Does that succed?

![grafik](https://user-images.githubusercontent.com/3088879/100555174-0975ce80-329a-11eb-97c0-748d724dc03b.png)

Here are my OBS settings. Would be helpful to get a better idea whether resolution and/or bitrate are causing the issue. 

![grafik](https://user-images.githubusercontent.com/3088879/100555226-4f329700-329a-11eb-85f3-a57c4c91cc6a.png)

**Comment by MerlinCooper** [comment]
@petarpav28 Have you been able to try with the settings I provided? Did it work? 

If yes could you try to change back to your settings step-by-step and provide more information what setting change in OBS triggers the error?
