### ISSUE TITLE
Generic Questions - Continuance from iRacing Forums

### ISSUE THREAD

**Issue by MarkB335** [MerlinCooper/iRacingReplayDirector#49]
Hello,

Per your request I thought I would put my issues with the file.

So 1st thanks for responding and adding in the Lap Number there.  I see how it works.  But it brought up a few more questions.

1). So having the fast recording checked and using OBS.  Does it record the events listed in the json under race events in order.  This is my assumption.  

2) I am also assuming the fast recording is hardkeyed to alt F9 as well.  Because right now it just does a continuous recording file.  I am assuming if I change my keybindings in OBS to alt F9 I will get x amount of clips corresponding to the number of RaceEvents listed in the json file.  Also regarding this I am not adverse to one big file anyways although it does take some time to breakdown the pause in the clips.  Especially for continuous clip action.  ie Last Night I got several clips that were basically just following the same person for a couple of laps (I believe it was a battle) but it was broken down into quite a few continuous clips of around 7.5 seconds.

3). Do you have a handy chart of what the numbers correspond to the clip type expressed in the Race Events breakdown.  Sorry I am at work typing this but it is an integer coded number like 1,3.  I can sort of figure it out from clips but just didn't know if you or anyone had a hard list somewhere.

4). Looking at issues here what exactly is the state of the fast recording in the main branch of the program?  Is the Fast_Video_Recording_with_OBS more up to date and less buggier?

**Comment by MerlinCooper** [comment]
Hi Mark, 

welcome to GitHub - will do my best to answer your questions and in case there is an issue we can create an issue report right away. As you might know I'm not the creator of the project and just jumped on it after Vipoo no longer being able to continue. Therefore some questions I will not be able to answer w/o digging into the source code. 

**ad 1)** You are right. At the moment the order how the events are being recorded is given by the sequence in the JSON file. At the moment there is no real possibility to change that (although it's being mentioned in the original version w/o the JSON format) - but as a future extension there might be some Race-Event Editor (allowing the user to modify sequence, picked events, etc.). But will not start working on that before the other functionalities are not reliably working

**ad 2)** Yes it's a keybinding in the source code (like for the original coding). But that should be easy to make that editable. 

**ad 3)**There is no overview of the data - when the class definition file. The values written to the JSON file is just a serialization of the variables of the classes. Not sure what value you are interested in specifically. Can you post as screenshot of the JSON file content?

**ad 4)** That depends. I'm primarily working on the Fast-Video-Coding project. But that doesn't mean that it has less issues than the previous version. I would consider the Fast-Video Coding as an alpha version - but merge that to the master branch from time to time to allow people to give it a try as well (and report issues I didn't find so far).

You can get an overview what's going on by looking at the [Network graph](https://github.com/MerlinCooper/iRacingReplayDirector/network). Ideally people do create an issue in GitHub for every bug they find - than the issues can be referenced when committing a code change and it will be shown in the change log. 

If you have further questions don't hesitate to ask. 


![image](https://user-images.githubusercontent.com/3088879/102687250-f9dd0c00-41ed-11eb-81eb-52cf4f6962b0.png)

**Comment by MarkB335** [comment]
Ok here is what I was refering to in the json about interest number code:
![Screen Shot 2020-12-22 at 10 29 40 AM](https://user-images.githubusercontent.com/76215952/102929541-cbb73080-4468-11eb-957e-603d28fb7fd1.png)
I can probably figure out through trial and error but didn't know if there was. a list somewhere I was missing.  One thing I did notice today and that is what is kinda throwing me off with the fast recording.  It seems to record by half the time listed.  

So I don't have a picture but Race Event 1 in the json says 15.2 seconds and change long.  The log in the capture.log shows this:

**2020-12-21T23:03:46	DEBUG: Camera switched to driver David Lougee using camera-group 18. Remaining Time: 12542
2020-12-21T23:03:59	DEBUG: Camera switched to driver David Lougee using camera-group 18. Remaining Time: 35473
2020-12-21T23:03:59	INFO: Sending key event to start/stopp recording ALT+F9
2020-12-21T23:04:01	INFO: ADV_RECORDING: Type: iRacingReplayDirector.Phases.Capturing.OverlayData+RaceEvent | Durations-Span: 7.6036744 | 
2020-12-21T23:04:01	INFO: Moving to frame 88531 with mode Begin
2020-12-21T23:04:01	INFO: Moved to frame 88531
2020-12-21T23:04:01	INFO: Setting speed to 1
2020-12-21T23:04:01	INFO: Sending key event to start/stopp recording ALT+F9
2020-12-21T23:04:01	DEBUG: Throttle message ReplaySetPlaySpeed delivery to iRacing by 985 millisecond
2020-12-21T23:04:03	DEBUG: Recording Race-Event. Frame-Position: 88531  | Duration: 7603.6744 ms
2020-12-21T23:04:11	INFO: Sending key event to start/stopp recording ALT+F9
2020-12-21T23:04:13	INFO: ADV_RECORDING: Type: iRacingReplayDirector.Phases.Capturing.OverlayData+RaceEvent | Durations-Span: 7.6036744 | 
2020-12-21T23:04:13	INFO: Moving to frame 88988 with mode Begin
2020-12-21T23:04:13	INFO: Moved to frame 88988
2020-12-21T23:04:13	INFO: Setting speed to 1
2020-12-21T23:04:13	INFO: Sending key event to start/stopp recording ALT+F9**

So it appears to be only recording half.  Now going through the video.  I can't quite make heads or tails of it but I have "extra clips" that explan it (or that I am interpreting the mp4 file wrong compared to what is listed in the events file)

Could this somehow be related to maybe being processed at 60 fps for the capture.log file compare to actually being recorded at 30 fps?

**Comment by MerlinCooper** [comment]
> 
> 
> Ok here is what I was refering to in the json about interest number code:
> ![Screen Shot 2020-12-22 at 10 29 40 AM](https://user-images.githubusercontent.com/76215952/102929541-cbb73080-4468-11eb-957e-603d28fb7fd1.png)
> I can probably figure out through trial and error but didn't know if there was. a list somewhere I was missing. 

No need to do that by trial and error - just looked it up in the source code. There is an enumeration data type defined which is used to classify the different event's. You can find that in the file RemovalEdits.cs. 

`public enum InterestState { Unknown = -1, None = 0, FirstLap = 1, LastLap = 2, Incident = 3, Restart = 4, Battle = 5 /*, Overtake = 5, Pitstp = 6 */};` 

Seems that "Overtake" and "PitStop" are currently not used. Anyway optimizing the event-detection might be one area of improvement for the future. But first I do want to get the Fast-Recording (still alpha) finished.

**Comment by MerlinCooper** [comment]
> 
> 
>One thing I did notice today and that is what is kinda throwing me off with the fast recording. It seems to record by half the time listed.
> 
> So I don't have a picture but Race Event 1 in the json says 15.2 seconds and change long. The log in the capture.log shows this:
> 
> **2020-12-21T23:03:46 DEBUG: Camera switched to driver David Lougee using camera-group 18. Remaining Time: 12542 2020-12-21T23:03:59 DEBUG: Camera switched to driver David Lougee using camera-group 18. Remaining Time: 35473 2020-12-21T23:03:59 INFO: Sending key event to start/stopp recording ALT+F9 2020-12-21T23:04:01 INFO: ADV_RECORDING: Type: iRacingReplayDirector.Phases.Capturing.OverlayData+RaceEvent | Durations-Span: 7.6036744 | 2020-12-21T23:04:01 INFO: Moving to frame 88531 with mode Begin 2020-12-21T23:04:01 INFO: Moved to frame 88531 2020-12-21T23:04:01 INFO: Setting speed to 1 2020-12-21T23:04:01 INFO: Sending key event to start/stopp recording ALT+F9 2020-12-21T23:04:01 DEBUG: Throttle message ReplaySetPlaySpeed delivery to iRacing by 985 millisecond 2020-12-21T23:04:03 DEBUG: Recording Race-Event. Frame-Position: 88531 | Duration: 7603.6744 ms 2020-12-21T23:04:11 INFO: Sending key event to start/stopp recording ALT+F9 2020-12-21T23:04:13 INFO: ADV_RECORDING: Type: iRacingReplayDirector.Phases.Capturing.OverlayData+RaceEvent | Durations-Span: 7.6036744 | 2020-12-21T23:04:13 INFO: Moving to frame 88988 with mode Begin 2020-12-21T23:04:13 INFO: Moved to frame 88988 2020-12-21T23:04:13 INFO: Setting speed to 1 2020-12-21T23:04:13 INFO: Sending key event to start/stopp recording ALT+F9**
> 
> So it appears to be only recording half. Now going through the video. I can't quite make heads or tails of it but I have "extra clips" that explan it (or that I am interpreting the mp4 file wrong compared to what is listed in the events file)
> 
> Could this somehow be related to maybe being processed at 60 fps for the capture.log file compare to actually being recorded at 30 fps?

Am I understanding you correctly that the recorded time in the highlight video is not the same duration than stated in the JSON file? If yes I'm pretty sure that this does not have to do anything with frame-rates (30FPS vs. 60FPS) your video is being recorded. 

Without having looked into the details I do remember that the capturing process does "shrink" the duration of the different highlights to fit them into the highlight video, e.g. 1 hrs race - 30 min highlight => 50% reduced duration. That might be why sometimes we are missing the most important part of an event. And if my hypothesis is correct that would get event worse when the difference between race-length and highlight video get's larger.

**Comment by MarkB335** [comment]
Did another one last night using the master branch fast recording feature.

Attached is the json file.  I have my highlight time set to 7 minutes.  The json Race Events in the json file total up to about 380 seconds or 6.34 minutes.  This produce a highlight raw video (which includes the intro and the pause bug which adds about a second) of 3:01 seconds.

So my assumption would be that since the total highlight time is approx 6.34 minutes and the highlight time is set to 7 minutes and factoring in about 30 seconds of intro screen this video should be roughly around 7 minutes.  Is that assumption incorrect?


[JSON FILE AND CAPTURE LOG.zip](https://github.com/MerlinCooper/iRacingReplayDirector/files/5735570/JSON.FILE.AND.CAPTURE.LOG.zip)

**Comment by MerlinCooper** [comment]
Would suggest to discuss generic questions int the [Discussion section](https://github.com/MerlinCooper/iRacingReplayDirector/discussions/new?category=announcements&welcome_text=true)
