### ISSUE TITLE
Transcoding with StandardOverlay fails

### ISSUE THREAD

**Issue by MerlinCooper** [MerlinCooper/iRacingReplayDirector#51]
see iRacing Forum for basic information. 
https://members.iracing.com/jforum/posts/list/175/3638321.page#12327955

@All: Please continue discussion in GitHub. iRacing Forum isn't really working for that purpose

**Comment by MerlinCooper** [comment]
Here is the replay file I would like everyone to test if the error still occurs. 
https://drive.google.com/file/d/10hj1YQ0p2ni1LVsYcwP6c4CKFJsolYN4/view?usp=sharing

Please provide as well the replay-file and the files generated by iRacingReplayDirector (e.g. Replayscript-file, JSON-file and MP4-file).

**Comment by mrzoops** [comment]
Do you want highlight video? How long? Should we be doing the fast recording or regular?

EDIT: Unfortunately I do not own Mid-Ohio so I cannot test this.

**Comment by MerlinCooper** [comment]
> Do you want highlight video? 
Does it generate a highlight video? I would assume that you just get the full-length video - because as I understood the failure happens at the start of the transcoding. When you can upload the replay file you are using it should be sufficient. 

>How long? Should we be doing the fast recording or regular?
Do recommend this settings. Will generate a very short highlight video - but at the end all code will be used. 
![image](https://user-images.githubusercontent.com/3088879/104073490-175e2e00-520e-11eb-8233-5ddd24f0ac57.png)

**Comment by MerlinCooper** [comment]
> 
> 
> Do you want highlight video? How long? Should we be doing the fast recording or regular?
> 
> EDIT: Unfortunately I do not own Mid-Ohio so I cannot test this.

No worries - then I will use your replay to figure out what is going wrong.

**Comment by aeon358** [comment]
Here's the files you asked for, Merlin. Replay file along with the generated files from the Replay Director. Hope this helps in some way.

[https://drive.google.com/file/d/1DtKmBkQgorZvYYcgQSIm3M8slrKzjicu/view?usp=sharing](url)

**Comment by MerlinCooper** [comment]
> 
> 
> Here's the files you asked for, Merlin. Replay file along with the generated files from the Replay Director. Hope this helps in some way.
> 
> [https://drive.google.com/file/d/1DtKmBkQgorZvYYcgQSIm3M8slrKzjicu/view?usp=sharing](url)

File is access protected. Did send you a request for read privileges via google drive.

**Comment by MerlinCooper** [comment]
Verified that transcoding with the StandardOverlays works starting with Package Version Draft-iRacingReplayDirector_20210107.7 by doing a very short highlight video from the replay you provided. 

https://drive.google.com/file/d/1XxOH1bx197bWgyVH0OcKK4xq-vcC5r27/view?usp=sharing

Can you please double-check what the version number in the about box you are using is? It's supposed to be 1.2.7677 (or greater). Furthermore double-check the name of the DLL in your .\Plugins\StandardOverlays Folder. If it doesn't look like in the screenshot below you might be running an older version. 

![image](https://user-images.githubusercontent.com/3088879/104118945-aeb9a300-532c-11eb-818e-a032584b22b8.png)

**Comment by MerlinCooper** [comment]
@aeon358 any update on that? Can you confirm that the issue is fixed. Works fine on my side.

**Comment by aeon358** [comment]
Hey man, sorry for not responding. Got caught up in some other stuff. But yes, everything is fixed and works fine now. Thank you for taking the time to help out.
