### ISSUE TITLE
Video stuttering with new fast encode

### ISSUE THREAD

**Issue by mrzoops** [MerlinCooper/iRacingReplayDirector#62]
Is this issue still being looked at? Its really the only thing keeping us from using the fast encode which is so much better.

**Comment by mrzoops** [comment]
Any update on this at all? Is this still being looked at?

**Comment by MerlinCooper** [comment]
Unfortunately I was quite busy and wasn‘t motivated to continue the project.

I do hunk I know what is causing the stutter - seems that some frames are played again when two interesting race situations are either close to each other or just the camera is changed.

Can’t promise anything but might have a look in 2022.

**Comment by MerlinCooper** [comment]
Could be the same issue like this
https://github.com/MerlinCooper/iRacingReplayDirector/issues/43
