### ISSUE TITLE
Non-supported sessions resulting in error "Abborts capture on Phoenix Dirt Track RallyCross"

### ISSUE THREAD

**Issue by trglenn** [MerlinCooper/iRacingReplayDirector#65]
Using version 20210111.1. Stops with :

Waiting to connect to iRacing application
Connected to iRacing application
Moving logging to file D:\iRacing Stuff\iRacing Videos\capture.log
Setting speed to 16
Moving to frame 25165 with mode Begin
iRacing failed to respond to message
   at iRacingSDK.Replay.WaitAndVerify(Func`2 verifyFn, Action action)
   at iRacingSDK.Replay.WaitAndVerify(Func`2 verifyFn)
   at iRacingSDK.Replay.MoveToFrame(Int32 frameNumber, ReplayPositionMode mode, Int32 tolerance)
   at iRacingReplayDirector.Phases.IRacingReplay.AnalyseIncidents()
   at iRacingReplayDirector.Phases.IRacingReplay._AnalyseRace(Action onComplete)
   at iRacingReplayDirector.Phases.IRacingReplay.<>c__DisplayClass40_0.<Add>b__0()
   at iRacingReplayDirector.Phases.IRacingReplay.<>c__DisplayClass58_0.<InTheBackground>b__0()
Process aborted
Moving logging to file D:\iRacing Stuff\iRacing Videos\general.log
[capture.log](https://github.com/MerlinCooper/iRacingReplayDirector/files/7785199/capture.log)

This is the only track I have found this issue on. Worked great with USA, Lanier, Limaland, Charlotte and Daytona. Please let me know if I can provide any thing else to help.

Thanks

**Comment by MerlinCooper** [comment]
At the point of time the application was created by Dean there wasn't even Dirt Racing available. 

Don't have a lot of time and will not be at home for the next 1 1/2 weeks. But if you upload a replay file I could have a look when I'm back. Not promising anything - but if a quick fix is possible I might be able to do that.

**Comment by trglenn** [comment]
Here is a link to the replay. [https://www.dropbox.com/s/3pdkba2r0fq0flj/subses43525196.zip?dl=0](https://www.dropbox.com/s/3pdkba2r0fq0flj/subses43525196.zip?dl=0)

I had to upload it to Dropbox. It would tell me "is not included in the list" when trying to upload it here.  Anyway thanks for looking at it and no hurry at all.  

Thanks,

**Comment by MerlinCooper** [comment]
No plans/resources to support other sessions than road-races and oval races.

will have a look whether I can add a session type verification and messagebox for users trying other replay sessions. If more developers joining the show we might be able to do implement an enhanced version
