### ISSUE TITLE
Pre-release version not sending ALT+F9 correctly

### ISSUE THREAD

**Issue by mrzoops** [MerlinCooper/iRacingReplayDirector#66]
When testing video capture using both nvidia shadowplay and/or OBS, IRD says it sends ALT+F9 but recording never starts. When manually typing ALT+F9, the recording starts. 

This is happening on both the new pre-releases that have been published. Old stable version working correctly.

**Comment by MerlinCooper** [comment]
@mrzoops Thanks for the feedback - seems that at least one is still following the activies here ;-)

Will have a look. Might have too many hotkeys configured in my OBS and therefore have not seen that failure in my quick tests.

**Comment by mrzoops** [comment]
FYI: still happening on 20220509.3

**Comment by MerlinCooper** [comment]
> FYI: still happening on 20220509.3

Yes - the other releases where just created because I had to test/fix some issue in the AzurePipeline as well.

**Comment by MerlinCooper** [comment]
@mrzoops Issue should be fixed with https://github.com/MerlinCooper/iRacingReplayDirector/releases/tag/20220510.1.

Would appreciate if you could double-check and confirm.

**Comment by mrzoops** [comment]
> @mrzoops Issue should be fixed with https://github.com/MerlinCooper/iRacingReplayDirector/releases/tag/20220510.1.
> 
> Would appreciate if you could double-check and confirm.

Confirmed!
