### ISSUE TITLE
maximum time exceeded

### ISSUE THREAD

**Issue by jkrilin** [MerlinCooper/iRacingReplayDirector#74]
Hello, I am trying to use the application but once everything is installed and the assets have been copied, when I set the maximum time of the video to be 8 minutes when rendering it, the program does not record that time as a maximum, but rather the entire race. Do I have something misconfigured? and also the overlays of the classification do not come out
![Sin título](https://user-images.githubusercontent.com/112321371/187074729-d1764830-0a40-4587-aa79-e13d0eadde31.png)

**Comment by mrzoops** [comment]
That time applies to the highlight video. It seems you are choosing the entire race and not the highlight video.

**Comment by jkrilin** [comment]
> Ese tiempo se aplica al video destacado. Parece que estás eligiendo toda la carrera y no el video destacado.

How do I select the featured video?
