### ISSUE TITLE
index outside the bounds of the array

### ISSUE THREAD

**Issue by jkrilin** [MerlinCooper/iRacingReplayDirector#75]
Hello, I have this problem when verifying the capture in the latest version of the program, and it is that when I am going to render it, I get this error and it does not let me do the test to have only the best moments. I Have Win 11

Switching to iRacing ....
Begining Test....
Broadcasting keypress Alt + F9 to activate your video capture software
Sending key event to start/stopp recording Alt + F9
Expecting video file to be written in folder: C:\Users\Jkrilin\Videos\
Waiting for 5 seconds
Found video file C:\Users\Jkrilin\Videos\2022-08-29 14-21-52.mp4
5 Seconds...
4 Seconds...
3 Seconds...
2 Seconds...
1 Seconds...
0 Seconds...
Broadcasting keypress Alt + F9 to deactivate your video capture software
Sending key event to start/stopp recording Alt + F9
Minimising iRacing

Found your video file C:\Users\Jkrilin\Videos\2022-08-29 14-21-52.mp4.
Frame Rate: 60, Frame Size: 1920x1080, Video: H264 @ 2Mbs, Audio: AAC, 48Khz @ 0Kbs, 
Begining video re-encoding.
Índice fuera de los límites de la matriz.
   en MediaFoundation.Net.SourceReader.<Samples>d__4.MoveNext()
   en MediaFoundation.Net.SourceReader.Samples(ProcessSample samplesFn, Int32 streamIndex, Int32 controlFlags)
   en MediaFoundation.Net.SourceReader.Samples(ProcessSample samplesFn)
   en iRacingReplayDirector.TestVideoCapture.<>c.<TranscodeVideoTest>b__10_0(IEnumerable`1 readers, ProcessSample saveToSink)
   en iRacingReplayDirector.Phases.Transcoding.Transcoder.ProcessVideo(Action`2 process)
   en iRacingReplayDirector.TestVideoCapture.TranscodeVideoTest(String filename)
   en iRacingReplayDirector.TestVideoCapture.RunTest(String workingFolder, SynchronizationContext context)

Do you know how to solve it? Thanks

**Comment by MerlinCooper** [comment]
Try to verify your setup first - if that failes you want get any video recorded/transcoded. 
https://github.com/MerlinCooper/iRacingReplayDirector/issues/79#issuecomment-1404639455

**Comment by MerlinCooper** [comment]
@jkrilin by the way the log file does contain again messages in language other then English. I am not aware about any multi-language support implemented in my forked repository. Are you sure that you did get the binaries from this fork?

**Comment by jkrilin** [comment]
> @jkrilin by the way the log file does contain again messages in language other then English. I am not aware about any multi-language support implemented in my forked repository. Are you sure that you did get the binaries from this fork?

I don't understand it either. I downloaded it from your github repository but I could not tell you why things come out in Spanish. It may be because of the language of Windows. But I wouldn't know how to tell you
