### ISSUE TITLE
only start and finsh in highlight video

### ISSUE THREAD

**Issue by Orakel1971** [MerlinCooper/iRacingReplayDirector#77]
i tried 4 different replays 3 Road and 1 Oval. My Duration for the HighlightReel is 10min. but my Highlightvideo is on about 2min long and it shows only the Start and the the Finish. nothing in between :-(
what going on here is it my fault or an issue 
I am using the latest Version und iracing is in the Season4 updated

i hope that someone knows what to do. i want to release these viedeos on youtube for our Discord Group

greets Orakel

**Comment by MerlinCooper** [comment]
Could you provide one of the mentioned replays? 

Then I could simply run a test and when it failes debug the software-code using Visual-Studio.

**Comment by Orakel1971** [comment]
i tried it with the new replayDirector and every replay i have saved from iracing is only 13seconds long. u see i car driving over the starting line and then u see a acar driving to the finish...nothing between.

https://drive.google.com/file/d/1a8PnlZ9XTlnjazbfKQAd_4qhGh-NDDU8/view?usp=sharing

**Comment by MerlinCooper** [comment]
Can't try it because do not own the track and will not buy any oval tracks - just doing road racing. 

What type of race is this? Dirt? Oval? Is it working with other replays?

Would you mind posting your "iracing-replay-director.settings" file which should be located in your /documents folder.

**Comment by Orakel1971** [comment]
Hi Merlin, suddenly it works and the HightlightVideo is about 8min long. It works on Road and Oval Replays. I dont know what happend and i cant say what i have done to get it work. U can closse this .

**Comment by MerlinCooper** [comment]
Good to hear.

you know that you can set the length of the highlight video generated in the settings dialog. For sure it makes sense that duration_highlight video < racelength
