### ISSUE TITLE
Error to re-encoder

### ISSUE THREAD

**Issue by jkrilin** [MerlinCooper/iRacingReplayDirector#79]
Hello, I am trying to use the app on my Windows 10 (64bit) but every time I do the recording test it gives me this error and I have tried everything and even reinstalling the program and deleting my document files.  Any solution?
![IMG_20221110_005055_445](https://user-images.githubusercontent.com/112321371/200966650-ef79f060-50d8-4812-849f-4304ce34fbc3.jpg)

**Comment by MerlinCooper** [comment]
Did you try testing whether your recording software is configured accordingly to the settings in iRacingReplayDirector? 

You can do that by clicking on the "Verify Video Capture" Button on the bottom right of the main dialog. 
![grafik](https://user-images.githubusercontent.com/3088879/214779311-13a5314b-a5f7-40f3-a630-250c662906aa.png)

Please make sure that the recording format is either .avi or .mp4. Then you should get the following result. 
![grafik](https://user-images.githubusercontent.com/3088879/214779517-b09b9151-5e08-40e3-864d-c3e75deda3ad.png)

P.S.: Just tested it this morning with the most recent version - but there was no code change since years in that area thus every version should work as intended.

**Comment by SoOlditHurts** [comment]
This was from the very first time I tried it. Honestly I don't remember my settings back then. I've since got it working all the time, except the "Fast Video Recording" mode which never works.

**Comment by jkrilin** [comment]
> Did you try testing whether your recording software is configured accordingly to the settings in iRacingReplayDirector?
> 
> You can do that by clicking on the "Verify Video Capture" Button on the bottom right of the main dialog. ![grafik](https://user-images.githubusercontent.com/3088879/214779311-13a5314b-a5f7-40f3-a630-250c662906aa.png)
> 
> Please make sure that the recording format is either .avi or .mp4. Then you should get the following result. ![grafik](https://user-images.githubusercontent.com/3088879/214779517-b09b9151-5e08-40e3-864d-c3e75deda3ad.png)
> 
> P.S.: Just tested it this morning with the most recent version - but there was no code change since years in that area thus every version should work as intended.

Where I have to put it in .avi or .mp4.? In the application itself or in the obs?

**Comment by MerlinCooper** [comment]
> Where I have to put it in .avi or .mp4.? In the application itself or in the obs?

The file format used for recording has to be set in your recording software - for OBS thats in the follwowing menu in the section recording. 
![grafik](https://user-images.githubusercontent.com/3088879/215028117-6399f5a1-92ff-4b32-ab13-9644dbba7a2c.png)

**Comment by jkrilin** [comment]
> > Where I have to put it in .avi or .mp4.? In the application itself or in the obs?
> 
> The file format used for recording has to be set in your recording software - for OBS thats in the follwowing menu in the section recording. ![grafik](https://user-images.githubusercontent.com/3088879/215028117-6399f5a1-92ff-4b32-ab13-9644dbba7a2c.png)

Hi, I just tried it and it still gives me the same problem. I am sending you a screenshot of the video verification, the error, the log and how I have it configured in the obs. I also noticed that when I click on start recording, the screen resolution in the game is lowered.
![correcto](https://user-images.githubusercontent.com/112321371/215355750-71fb2598-94a9-4430-aa93-b725b25140ca.png)
![error](https://user-images.githubusercontent.com/112321371/215355755-d42b0505-caed-402f-a047-fac4c0e30f3d.png)
[log.txt](https://github.com/MerlinCooper/iRacingReplayDirector/files/10530865/log.txt)
![image](https://user-images.githubusercontent.com/112321371/215355779-ee779226-de7e-42c4-9f33-1b671a4bc9f7.png)

**Comment by MerlinCooper** [comment]
Can you please post a screenshot of the dialog shown when clicking on the button ‚About…‘

**Comment by MerlinCooper** [comment]
What‘s contained in the generated mp4-file? Looks like just the message is a false positive - because the error log doesn‘t contain an error message.

From where did you download the executable? Are you using the most recent version? Don‘t remember supporting any other language than English.

**Comment by jkrilin** [comment]
>What‘s contained in the generated mp4-file? Looks like just the message is a false positive - because the error log doesn‘t contain an error message.
>
>From where did you download the executable? Are you using the most recent version? Don‘t remember supporting any other language than English.

Download it from your own page in the latest version you uploaded yesterday. The obs is the only thing I have in Spanish the rest is all in English 

![image](https://user-images.githubusercontent.com/112321371/215424585-2fbaebfb-9081-4516-b782-b826e3adca8a.png)

**Comment by jkrilin** [comment]
when I do a test or when I click on the recording button, the iracing screen appears as follows
![image](https://user-images.githubusercontent.com/112321371/215424841-b8d8cfdd-f1c2-464f-be9b-36a042320797.png)

**Comment by MerlinCooper** [comment]
> when I do a test or when I click on the recording button, the iracing screen appears as follows
> ![image](https://user-images.githubusercontent.com/112321371/215424841-b8d8cfdd-f1c2-464f-be9b-36a042320797.png)

^ that looks good so far. And when does the error occur?

p.s.: still wonder how the error message appears in Spanish but it‘s not the most important topic.

**Comment by jkrilin** [comment]
> > cuando hago una prueba o cuando hago clic en el botón de grabación, la pantalla de iracing aparece de la siguiente manera
> > ![imagen](https://user-images.githubusercontent.com/112321371/215424841-b8d8cfdd-f1c2-464f-be9b-36a042320797.png)
> 
> ^ que se ve bien hasta ahora. ¿Y cuándo se produce el error?
> 
> pd: todavía me pregunto cómo aparece el mensaje de error en español, pero no es el tema más importante.

It's just when you're going to make the video 
I'm going to record the whole process and upload it to YouTube for you to see.

**Comment by jkrilin** [comment]
> > when I do a test or when I click on the recording button, the iracing screen appears as follows
> > ![image](https://user-images.githubusercontent.com/112321371/215424841-b8d8cfdd-f1c2-464f-be9b-36a042320797.png)
> 
> ^ that looks good so far. And when does the error occur?
> 
> p.s.: still wonder how the error message appears in Spanish but it‘s not the most important topic.

I think I already found the fault and it was because the pause key is not configured and that's why it failed. Once added that key to both the obs and the app no longer gives me an error but now for example it does not show me the overlays. Can I pass some screenshots of how they have configured the application and the obs to leave it as it is and try it? As if you can pass me the link of the application you have to have everything the same.

**Comment by MerlinCooper** [comment]
There are no overlays possible when using the fast recording - so that wouldn‘t be an issue.

If you like to have an overlay just use one you usually use when driving or streaming

**Comment by MerlinCooper** [comment]
Failure that no default key is set will be tracked in issue #90

**Comment by jkrilin** [comment]
> There are no overlays possible when using the fast recording - so that wouldn‘t be an issue.
> 
> If you like to have an overlay just use one you usually use when driving or streaming

How do I have to configure it so that I get the overlays of it?

**Comment by MerlinCooper** [comment]
Two possible ways to get an overlay depending whether you use fast-recording or not.

(A) when using fast encoding use a standard overlay like together with OBS
(B) unstick fast-Recording and select a plugIn in the configuration dialog. At the bottom should be a list which likely currently says no overlay

**Comment by mrzoops** [comment]
So I know it’s been brought up before is there no actual way to get overlays with fast encoding at some point? It just defeats the purpose of having this great tool. Ideally it would be an all in one replay maker without need for anything else.

**Comment by MerlinCooper** [comment]
> So I know it’s been brought up before is there no actual way to get overlays with fast encoding at some point? It just defeats the purpose of having this great tool. Ideally it would be an all in one replay maker without need for anything else.

No - I don't see an easy way how to do that. Furthermore every style would require somebody to program that in C#. Much easier that you use an overlay program you anyway likely use if you do stream. 

But hey - it is open source, so everyone can create a fork and give it a try to incorporate that to the fast-recording process.
