### ISSUE TITLE
Make Check Boxes Persistant

### ISSUE THREAD

**Issue by SoOlditHurts** [MerlinCooper/iRacingReplayDirector#80]
It doesn't maintain checkbox persistence between program starts. Both in Race Capture and Video Encoding. It would be more intuitive if it did.

**Comment by MerlinCooper** [comment]
@SoOlditHurts Would you mind adding a screenshot what settings you are proposing? Do you think we do need a reset to default button as well - just in case people mess up the settings?

**Comment by SoOlditHurts** [comment]
Pretty much all the checkboxes on the main screens. It always starts with Fast Video Recording, which doesn't work for me. And on the Video Encoding screen, the Highlight Video Only is always checked. For my purposes, I want to create a full video and don't want the highlight video. I'm always checking "Encode video after capture" and unchecking "Highlight video only" every time.

There are so few, I don't think you need a reset. Once people settle on how they use it, they'll probably want it to do the exact same thing every time.

![Screenshot 2023-01-26 075004](https://user-images.githubusercontent.com/83684120/214853082-3693c406-66b4-45a1-9bb1-5d6fed91f37f.jpg)
![Screenshot 2023-01-26 075010](https://user-images.githubusercontent.com/83684120/214853101-a32c9670-1562-4018-8030-71f890d323cb.jpg)

**Comment by MerlinCooper** [comment]
@SoOlditHurts You can finde a pre-release which incorporates your requested changes here. 

https://github.com/MerlinCooper/iRacingReplayDirector/releases/tag/20230127.1

Would be great to get feedback from you on short notice. Otherwise the changes will be incorporated into the next weekly release automatically (with just the brief testing I did).

**Comment by SoOlditHurts** [comment]
That works! Tested checkbox persistence every which way and it’s perfect.
