### ISSUE TITLE
End of Life?

### ISSUE THREAD

**Issue by SoOlditHurts** [MerlinCooper/iRacingReplayDirector#81]
Just curious if future development is planned or if this has reached its end of life.

**Comment by MerlinCooper** [comment]
Going slowly - being the only one working on the stuff doesn't help speed and motivation. 

But never say never

**Comment by SoOlditHurts** [comment]
I get that! I've started using it twice a week so I can test the hell out of it.

**Comment by MerlinCooper** [comment]
Finding people to test the software is not that difficult - fixing the issues and getting the meanwhile quite old code maintained is more time consuming. Unfortunately there is no real developer-base available and the code from vipoo could be much easier today based on new features in Visual-Studio available. But do not want to spend the time to rework everything.
