### ISSUE TITLE
Fast Recording Alpha Issue

### ISSUE THREAD

**Issue by SoOlditHurts** [MerlinCooper/iRacingReplayDirector#84]
I did a test using the 20230127.1 version and while it did complete the Capture, the resulting replayscript comes back with “Error reading the video file. Sequence contains no elements.” I noticed the “VideoFiles” value in the json is “null”. This happened both with the Short Test both Off and On. Tested it both ways. 

Zip file was too big to attach so [here is a link](https://1drv.ms/u/s!AljcDBdefjsGiMse9uJ6VEyigGhgwg?e=3SKAZ4). It contains the results from both tests. Link expires Jan 31.

**Comment by MerlinCooper** [comment]
Hmm - looking into the zip-file two MP4 files have been generated. Looks like they are from both attempts. What length of the highlight video did you set? Thus the error message might be just a false positive. Would you mind sharing the replay file as well. Could try to generate a 5-10 min highlight video as well and see whether I get the same issue. 

The generated video is not really useful. Just too many jumping and stuttering between the different scenes - but that's current stage of development.  

P.S.: Short-Test and "Fast Recording" together don't make sense. Short test is helpful to doublecheck. If you don't mind please use most recent pre-release - the latest contains a warning that for other then oval and road sessions the application was never tested. As mentioned when this app was started by another guy there was no other sessions than oval, road. Did get some feedback that heats are not working so might, sooner or later, just disable the Capture button for those scenarios.

**Comment by MerlinCooper** [comment]
Most recent pre-release is [Pre-release_20230128.3](https://github.com/MerlinCooper/iRacingReplayDirector/releases/tag/20230128.3)

**Comment by SoOlditHurts** [comment]
Tried with the 128.3 release with the same result. I tried a 5 minute highlight video and a different replay file this time. I can put together the results and replay file for you if you want. Personally, if I were you, I wouldn't spend much time on this Fast Recording process at this stage in the tool. In fact, I'd remove it from the tool as is. 

I think the tool as-is is pretty slick and can use some a few updates that might help to broaden appeal.

**Comment by MerlinCooper** [comment]
> Tried with the 128.3 release with the same result. I tried a 5 minute highlight video and a different replay file this time. I can put together the results and replay file for you if you want. Personally, if I were you, I wouldn't spend much time on this Fast Recording process at this stage in the tool. In fact, I'd remove it from the tool as is.
> 
> I think the tool as-is is pretty slick and can use some a few updates that might help to broaden appeal.

Well the "Fast-Recording-Option" is the only reason why I'm doing something on the iRacingReplayDirector. Just try to do a 15 min highlight video from an 3 hrs endurance race and you will understand what I mean. Would take more than 6 hrs to create with the approach vipoo took to fully play out the replay twice. 

With the fast recording approach it's just 16x fast-forward (675 sec) + Recording of the identified highlights (900 sec) + some overhead (90 sec) = 1665 sec -> less than 30 min.

**Comment by MerlinCooper** [comment]
> Tried with the 128.3 release with the same result. I tried a 5 minute highlight video and a different replay file this time. I can put together the results and replay file for you if you want. Personally, if I were you, I wouldn't spend much time on this Fast Recording process at this stage in the tool. In fact, I'd remove it from the tool as is.

Yes would appreciate if you could provide as much information as possible - just did a quick test of a 5 min Highlight as well. 

Here is what I get - using a cut replay where the end of the race is not in for testing purpose. 
https://youtu.be/0uQC5B7Fcd8

Not exactly 5 min long (a little longer) due to still some issues with regard length of pre/post-race videos.

Could you please verify your OBS settings (hotkey and recording). Here are mine for reference. 
![grafik](https://user-images.githubusercontent.com/3088879/215316732-b7afb96a-5f77-4745-a45d-96cc4d63615e.png)
![grafik](https://user-images.githubusercontent.com/3088879/215316758-0e980375-a426-4b90-9fd7-7d31ec8a502a.png)

Do you have the OBS-Status bar visible - does it change from time to time between REC and PAUSE? Is the counter increasing?
![grafik](https://user-images.githubusercontent.com/3088879/215316810-404a2190-6501-450f-8497-bd528d56d805.png)
![grafik](https://user-images.githubusercontent.com/3088879/215316839-030f046e-1294-4f7d-894b-55daffc58d81.png)
![grafik](https://user-images.githubusercontent.com/3088879/215316867-a2f6c8f3-6972-4b48-a513-d4a64236e692.png)

**Comment by SoOlditHurts** [comment]
The process creates a captured video and seems to end without any errors.  It records and pauses. It just can't be encoded. 

![image](https://user-images.githubusercontent.com/83684120/215348311-7f509839-2221-41ea-ab41-30701bdf624e.png)


My OBS settings:
![image](https://user-images.githubusercontent.com/83684120/215347840-74064e65-c06c-4caa-99ac-4f7216d3b10b.png)
![image](https://user-images.githubusercontent.com/83684120/215347869-15ad9260-c789-4545-bad7-87f5122823ef.png)

Here is a link to the replay file I used and the files created when I did the Fast Video Recording: https://drive.google.com/drive/folders/1b3DGhbAe-dCi6HNaMaV8mB8VObgcDKoO?usp=sharing

My settings in the Config:
![image](https://user-images.githubusercontent.com/83684120/215348176-d77000af-4571-4fda-b616-35a5cc44163e.png)
![image](https://user-images.githubusercontent.com/83684120/215348189-1d66b3e3-51d3-4910-9593-a3c7f221db12.png)

**Comment by MerlinCooper** [comment]
There is no encoding required when you use fast-video-recording. If you like to have overlays - that would be the only reason why encode the recorded video again - you should use some overlays directly in OBS when recording first time
