### ISSUE TITLE
New Readme

### ISSUE THREAD

**Issue by SoOlditHurts** [MerlinCooper/iRacingReplayDirector#86]
I created a New Readme if you want to use it 
https://docs.google.com/document/d/1_6Ne2S_vf8JQTq0DvRWig-QOxEKYmTe3MdyGFaIfTdM/edit?usp=sharing

**Comment by MerlinCooper** [comment]
Can't access the link: 
![grafik](https://user-images.githubusercontent.com/3088879/215313199-d9283112-04cc-4cca-94f9-8324481441b5.png)

But anyway I appreciate any contribution to the github project. Do you know how fork the repository in GitHub? Afterwards you could change the readme directly in your fork the readme and do a pull-request - make sure that the pull request goes to "MerlinCooper/iRacingReplayDirector" master branch.

**Comment by SoOlditHurts** [comment]
Sorry, I don’t know how to fork it. Here is a link that should work.

https://docs.google.com/document/d/1_6Ne2S_vf8JQTq0DvRWig-QOxEKYmTe3MdyGFaIfTdM/edit?usp=sharing

**Comment by MerlinCooper** [comment]
Now I can read it - but unfortunately all the formating is lost when I copy the text into the readme on GitHub and I am too lazy to redo this. 

P.S.: Forking is quite easy - just click on fork on the top/right off the screen when you are on the project site
![grafik](https://user-images.githubusercontent.com/3088879/215332547-765b459d-8d70-4042-8c1d-c7b4de0df2c9.png)

Afterwards you can directly on GitHub Edit the readme and commit the changes. 

After commiting you can Trigger a pullrequest. 

No worries you can't break anything - and if something goes wrong there is always a way back to the previous version. That's what version control software is supposed to do ;-)

**Comment by SoOlditHurts** [comment]
Done.

**Comment by MerlinCooper** [comment]
Pull-Request accepted - just moved the CI/CD information to the top and formated that as table because that's usually the first thing I look at when opening the GitHub project. Artefacts are only valid and usefull if the compile status is o.k.
