### ISSUE TITLE
Video Encoding fails in newest release

### ISSUE THREAD

**Issue by SoOlditHurts** [MerlinCooper/iRacingReplayDirector#91]
Downloaded the new release (20230130.1) and did a Race Capture, NOT using Fast Video Recording. It completed successfully. When I then attempted to do the Video Encoding, it starts but fails with" ERROR: Could not load file or assembly 'StandardOverlays, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)". 

I then did a Video Encode on the files produced in the previous step, using the last version 20220606.1. It completed the Video Encoding successfully.
I've attached the general.log file for the failed attempt.
[general.log](https://github.com/MerlinCooper/iRacingReplayDirector/files/10561398/general.log)

**Comment by MerlinCooper** [comment]
Please double-check whether you expanded the PlugIns subdirectory as well and that there is a plugins folder contains the following files. I just unzipped the latest release and the files are definitely there. 
![grafik](https://user-images.githubusercontent.com/3088879/216173588-0e732a16-66d7-4626-a9f3-ed235a2b08c2.png)

If the files are there please go to "Configure General" and select a different overlay. Does it not work with all the different overlays? Or just not with the Standard-Overlay?

**Comment by MerlinCooper** [comment]
did a quick test on my side - doesn't seem to work with any type of overlay. Will have to do more detailed analysis - will not be able to do that before weekend.

**Comment by SoOlditHurts** [comment]
I noticed the YamlDotNet.dll files between versions don't match in size so I decided to run a test. I replaced the StandardOverlays directory from 2023 with the one from 2022. Then Video Encoding works. Just more info for you.

**Comment by MerlinCooper** [comment]
Seems to work when compiled in the VSS-IDE but not using the DevOps Pipeline.

**Comment by MerlinCooper** [comment]
Can confirm that it only failes if the artefacts are compiled using the Azure DevOps pipeline. Don't have any explanation at the moment - do hope that somebody at "stackoverflow" can help

https://stackoverflow.com/questions/75345775/different-behaviour-of-application-when-compiled-in-vss-and-azure-devops

**Comment by MerlinCooper** [comment]
@SoOlditHurts Found the root-cause for the failure. The assembly doesn't load due to microsoft security features. Very likely my directories I use when working with VisualStudio are unblocked by default. 

Don't have a solution at the moment but as a temporary containment action you can manually unblock the dll's provided. You need to do that for every DLL. 
![grafik](https://user-images.githubusercontent.com/3088879/216814871-2afb5c6b-cf7c-41f4-8df7-c7108a96ebf8.png)
