### ISSUE TITLE
cannot connect to iracing

### ISSUE THREAD

**Issue by mrzoops** [MerlinCooper/iRacingReplayDirector#99]
All of a sudden, using the newest build I cannot connect to iracing. When clicking on logs button the program freezes and crashes.

Tried with previous versions as well and same thing. 

 Is there a log file written somewhere I can provide for information?

**Comment by MerlinCooper** [comment]
@mrzoops Seems that something went wrong in the Azure CI/CD pipeline when I was experimenting with the code-signing options. Could you try whether this pre-release works on your side as  well. 

https://github.com/MerlinCooper/iRacingReplayDirector/releases/tag/20230223.3

This is how it looks on my side. 
![grafik](https://user-images.githubusercontent.com/3088879/221027930-c56f9778-f785-4c12-92d7-5e69778a5d42.png)

**Comment by MerlinCooper** [comment]
P.S.: Manual unblocking the plugin DLL is still required.

**Comment by mrzoops** [comment]
Yes working now. Thank you.

**Comment by MerlinCooper** [comment]
There still seems to be an issue - will have a look this weekend

**Comment by MerlinCooper** [comment]
Fixed by updating/modifing AzureDevOps Pipelines and Nugets used.
